version: '3.8'


networks:
  laravel:
    driver: local
  # ttt72_net: null

volumes:
  caddy_caddyfile:
    driver: bridge
#    driver: local

services:

  caddy:
    container_name: caddy
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/config:/config/caddy
#      - ${FOLDER_UPR_SERV}/storage/app/caddy:/etc/caddy
      - caddy_caddyfile:/etc/caddy
#      - caddy_caddyfile:/caddy/Caddyfile
#      - caddy_caddyfile:/caddy
#      - caddy_caddyfile:/etc/caddy
#      - caddy_caddyfile:./caddy
#      - caddy_caddyfile:/etc/caddy/Caddyfile
#      - caddy_caddyfile:/caddy
#      - caddyfile:/caddy/Caddyfile
#      - '${FOLDER_UPR_SERV}/storage/app/caddyfile33/:/etc/caddy/Caddyfile'
##      - '${FOLDER_2308BEGET}:/2308beget'
##      - '${FOLDER_2309LIVEWIRE}:/2309livewire'
##      - '${FOLDER_TEST231012}:${FOLDER_TEST231012_SERV}'
#      - '${FOLDER_2302DIDRIVE}:${FOLDER_2302DIDRIVE_CADDY}'
      - '${FOLDER_2309LIVEWIRE}:${FOLDER_2309LIVEWIRE_SERV}'
      - '${FOLDER_TEST23116PHP}:${FOLDER_TEST23116PHP_SERV}'
      - '${FOLDER_UPR_SERV}:${FOLDER_UPR_SERV_SERV}'
#      -  '/etc/caddy/Caddyfile:${FOLDER_UPR_SERV_SERV}/storage/app/caddyfile2'
#      -  './caddy/Caddyfile:${FOLDER_UPR_SERV_SERV}/storage/app/caddyfile2'

    depends_on:
      - db_mysql
#      - 2308beget
      - 2309livewire
#      - test231012
#      - 2302didrive
#      - test231116php
      - upr_serv
    networks:
      - laravel

#  redis:
#    container_name: redis
#    image: redis:latest
#    networks:
#      - laravel
#    ports:
#      - "6379:6379"
##    volumes:
##      - '${MYSQL_DB_FOLDER}:/var/lib/mysql'
#    restart: unless-stopped

#
#  memcached:
#    container_name: memcached
#    image: memcached:latest
#    networks:
#      - laravel
##    environment:
##      MYSQL_ROOT_HOST: "%"
##      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
#    ports:
#      - "11211:11211"
##    volumes:
##      - '${MYSQL_DB_FOLDER}:/var/lib/mysql'
#    restart: unless-stopped



  db_mysql:
    container_name: db_mysql
    image: mariadb:10.7.8
    networks:
      - laravel
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - '${MYSQL_DB_FOLDER}:/var/lib/mysql'
    restart: unless-stopped



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db_mysql:db
    ports:
      - 6060:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - db_mysql
    networks:
      - laravel




  2309livewire:
    container_name: 2309livewire
    depends_on:
      - db_mysql
    networks:
      - laravel
    build:
      context: .
      #      dockerfile: docker.2308beget.Dockerfile
      dockerfile: docker.2309livewire.Dockerfile
    working_dir: ${FOLDER_2309LIVEWIRE_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_2309LIVEWIRE_SERV}
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - '${FOLDER_2309LIVEWIRE}:${FOLDER_2309LIVEWIRE_SERV}'



  upr_serv:
    container_name: upr_serv
    depends_on:
      - db_mysql
    networks:
      - laravel
    build:
      context: .
      #      dockerfile: docker.2308beget.Dockerfile
      dockerfile: docker.laravel.Dockerfile
    working_dir: ${FOLDER_UPR_SERV_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_UPR_SERV_SERV}
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - '${FOLDER_UPR_SERV}:${FOLDER_UPR_SERV_SERV}'
      - caddy_caddyfile:${FOLDER_UPR_SERV_SERV}/storage/app/caddy

#      - './caddy/Caddyfile:/caddy/Caddyfile'
#      - './caddy/config:/caddy/config'
#      - '${FOLDER_UPR_SERV}/storage/app/caddyfile33/:${FOLDER_UPR_SERV}/storage/app/caddyfile33/'
#      - './caddy/Caddyfile:${FOLDER_UPR_SERV_SERV}/storage/app/caddyfile2'



#  2302didrive:
#    container_name: 2302didrive
#
#    build:
#      context: .
#      dockerfile: ${DOCKERFILE_2302DIDRIVE}
#    working_dir: ${FOLDER_2302DIDRIVE_CADDY}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#      - FOLDER=${FOLDER_2302DIDRIVE_CADDY}
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_2302DIDRIVE}:${FOLDER_2302DIDRIVE_CADDY}'
#
#    depends_on:
#      - db_mysql
#    networks:
#      - laravel




#  2308beget:
#    container_name: 2308beget
#
#    build:
#      context: .
#      dockerfile: docker.2308beget.Dockerfile
#    working_dir: /2308beget
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_2308BEGET}:/2308beget'
#
#    depends_on:
#      - db_mysql
#    networks:
#      - laravel




#  rosoweb:
#    container_name: rosoweb
#    depends_on:
#      - db_mysql
#    networks:
#      - laravel
#    build:
#      context: .
#      dockerfile: docker.rosoweb.Dockerfile
#    working_dir: ${FOLDER_ROSOWEB_SERV}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#      - FOLDER=${FOLDER_ROSOWEB_SERV}
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_ROSOWEB}:${FOLDER_ROSOWEB_SERV}'




#  site2311ar:
#    container_name: site2311ar
#    depends_on:
#      - db_mysql
#    networks:
#      - laravel
#    build:
#      context: .
#      dockerfile: docker.site2311ar.Dockerfile
#    working_dir: ${FOLDER_2311AR_SERV}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#      - FOLDER=${FOLDER_2311AR_SERV}
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_2311AR}:${FOLDER_2311AR_SERV}'




#  2311adminator:
#    container_name: 2311adminator
#    depends_on:
#      - db_mysql
#    networks:
#      - laravel
#    build:
#      context: .
#      dockerfile: docker.2311adminator.Dockerfile
#    working_dir: ${FOLDER_2311ADMINATOR_SERV}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#      - FOLDER=${FOLDER_2311ADMINATOR_SERV}
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_2311ADMINATOR}:${FOLDER_2311ADMINATOR_SERV}'





#  test231116php:
#    container_name: test231116php
##    depends_on:
##      - db_mysql
#    networks:
#      - laravel
#    build:
#      context: .
#      dockerfile: docker.test231116php.Dockerfile
#    working_dir: ${FOLDER_TEST23116PHP_SERV}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#      - FOLDER=${FOLDER_TEST23116PHP_SERV}
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_TEST23116PHP}:${FOLDER_TEST23116PHP_SERV}'





#  test231012:
#    container_name: test231012
#    depends_on:
#      - db_mysql
##      - memcached
##      - redis
##    links:
##      - memcached:Memcached
#    networks:
#      - laravel
#    build:
#      context: .
#      dockerfile: ${TEST231012_DOCKERFILE}
#    working_dir: ${FOLDER_TEST231012_SERV}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_TEST231012}:${FOLDER_TEST231012_SERV}'






# volumes:
#   caddy_certs:
# #   # scr:
# #   Caddyfile:
# #   # dataredis:
# #   v_mysql:
# #   data-www:
# #   www47:
# #   config:
# #   bu72_front:


